parameters:
    guardian_api.url: http://content.guardianapis.com/
    guardian_api.search_page: search
    guardian_api.key: q5kmfff8753v6q2kfq7m3rgu
    guardian_api.order_by: new

services:

    app.query:
        class: AppBundle\Utils\Query
        arguments:
            - @service_container
            - @logger

    app.storage:
        class: AppBundle\Utils\Storage